# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"

  # Проброс портов
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081

  config.vm.provider "virtualbox" do |vb|
    vb.name = "task2_1"
    vb.memory = "512"
  end

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y apache2 php libapache2-mod-php
        sudo echo 'Listen 8081' >> /etc/apache2/ports.conf

        sudo cp /vagrant/index.html /var/www/html/
        sudo mkdir /var/www/html/php/
        sudo cp /vagrant/index.php /var/www/html/php/
        sudo cp /vagrant/000-default.conf /etc/apache2/sites-available/

        sudo systemctl enable apache2
        sudo systemctl restart apache2
  SHELL
end