apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wcg-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: wcg-project

  source:
    repoURL: 'https://github.com/aleksandrhirs/devops-hometasks.git'
    targetRevision: main
    path: 12-helm

    helm:
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      parameters:
      - name: "service.port"
        value: "8888"
      - name: "replicaCount"
        value: "1"

      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      # valueFiles:
      # - values-dev.yaml

      # Values file as block file
      values: |
        # replicaCount: 2

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true