---
version: '3.3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    networks:
      - dark-net
    ports:
      - "8080:8080"
    depends_on:
      - nexus
  nexus:
    build:
      context: .
      dockerfile: Dockerfile.nexus
    networks:
      - dark-net
    ports:
      - "8081:8081"
networks:
  dark-net: {}