apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-cloud-generator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word-cloud-generator
  template:
    metadata:
      labels:
        app: word-cloud-generator
    spec:
      containers:
      - name: wcg
        image: ghcr.io/aleksandrhirs/wcg:32c1974ce0487a18932e42c1e5ce934c1df85b93
        ports:
        - containerPort: 8888