Vagrant.configure("2") do |config|

    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.define "master" do |master|
        master.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus   = 2
            vb.name = "jenkins_vm"
        end
        master.vm.hostname = "jenkins.vm"
        master.vm.network "forwarded_port", guest: 8080, host: 8080
        master.vm.network "private_network", ip: "192.168.33.10"

        master.vm.provision :ansible_local do |ansible|
            ansible.playbook       = "playbook.yaml"
            ansible.limit          = "all"
            ansible.inventory_path = "inventory"
        end
    end
end