# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8s"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 512
        vb.cpus   = 1
    end

    config.vm.define "slave1" do |slave|
        slave.vm.network "private_network", ip: "192.168.50.5"
        slave.vm.hostname = "slave1.puppet"
        slave.vm.provider("virtualbox") { |vb| vb.name = "slave1_puppet" }
    end

    config.vm.define "slave2" do |slave|
        slave.vm.network "private_network", ip: "192.168.50.10"
        slave.vm.hostname = "slave2.puppet"
        slave.vm.provider("virtualbox") { |vb| vb.name = "slave2_puppet" }
    end

    config.vm.define "slave3" do |slave|
        slave.vm.network "private_network", ip: "192.168.50.12"
        slave.vm.hostname = "mineserver.puppet"
        slave.vm.provider("virtualbox") { |vb| vb.name = "mineserver_puppet" }
    end

    config.vm.define "master", primary: true do |master|
        master.vm.network "forwarded_port", guest: 80, host: 8080
        master.vm.network "forwarded_port", guest: 8080, host: 8080
        master.vm.network "forwarded_port", guest: 8081, host: 8081
        master.vm.network "private_network", ip: "192.168.50.15"
        master.vm.hostname = "master.puppet"
        master.vm.provider "virtualbox" do |vb|
            vb.name = "master_puppet"
            vb.memory = "1536"
        end

        master.vm.provision :file, source: '.vagrant/machines/slave1/virtualbox/private_key', destination: '/home/vagrant/private_key_slave1'
        master.vm.provision :file, source: '.vagrant/machines/slave2/virtualbox/private_key', destination: '/home/vagrant/private_key_slave2'
        master.vm.provision :file, source: '.vagrant/machines/slave3/virtualbox/private_key', destination: '/home/vagrant/private_key_slave3'
        master.vm.provision :ansible_local do |ansible|
            ansible.playbook       = "playbook.yaml"
            ansible.limit          = "all"
            ansible.inventory_path = "inventory"
        end
    end
end