# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.define "node0" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "task3_1_static"
            vb.memory = "1024"
        end
        node.vm.network "private_network", ip: "192.168.33.9"
    end

    config.vm.define "node1" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "task3_2_dynamic"
            vb.memory = "1024"
        end
        node.vm.network "private_network", ip: "192.168.33.10"
    end

    config.vm.define "node2" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "task3_3_nginx"
            vb.memory = "1024"
        end
        node.vm.network "forwarded_port", guest: 80, host: 8080
        node.vm.network "forwarded_port", guest: 8080, host: 8080
        node.vm.network "forwarded_port", guest: 8081, host: 8081
        node.vm.network "private_network", ip: "192.168.33.11"

        node.vm.provision :file, source: '.vagrant/machines/node0/virtualbox/private_key', destination: '/home/vagrant/private_key_node0'
        node.vm.provision :file, source: '.vagrant/machines/node1/virtualbox/private_key', destination: '/home/vagrant/private_key_node1'

        node.vm.provision :ansible_local do |ansible|
            ansible.playbook       = "playbook.yaml"
            ansible.limit          = "all"
            ansible.inventory_path = "inventory"
        end
    end
end