Vagrant.configure("2") do |config|

    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 256
        vb.cpus   = 1
    end

    config.vm.define "nexus" do |nexus|
        nexus.vm.network "private_network", ip: "192.168.33.90"
        nexus.vm.network "forwarded_port", guest: 8081, host: 8081
        nexus.vm.hostname = "nexus"

        nexus.vm.provider "virtualbox" do |vb|
            vb.memory = 1500
            vb.name = "nexus_vm"
        end
    end

    config.vm.define "staging" do |staging|
        staging.vm.network "private_network", ip: "192.168.33.80"
        staging.vm.hostname = "staging"
        staging.vm.provider("virtualbox") { |vb| vb.name = "staging_vm" }
    end

    config.vm.define "production" do |production|
        production.vm.network "private_network", ip: "192.168.33.85"
        production.vm.hostname = "production"
        production.vm.provider("virtualbox") { |vb| vb.name = "production_vm" }
    end

    config.vm.define "master" do |master|
        master.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.name = "jenkins_vm"
        end
        master.vm.hostname = "master"
        master.vm.network "forwarded_port", guest: 8080, host: 8080
        master.vm.network "private_network", ip: "192.168.33.100"

        master.vm.provision :file, source: '.vagrant/machines/nexus/virtualbox/private_key', destination: '/home/vagrant/private_key_nexus'
        master.vm.provision :file, source: '.vagrant/machines/staging/virtualbox/private_key', destination: '/home/vagrant/private_key_staging'
        master.vm.provision :file, source: '.vagrant/machines/production/virtualbox/private_key', destination: '/home/vagrant/private_key_production'

        master.vm.provision :ansible_local do |ansible|
            ansible.playbook       = "playbook.yaml"
            ansible.limit          = "all"
            ansible.inventory_path = "inventory"
        end
    end
end