apiVersion: v1
kind: Service
metadata:
  name: {{ include "word-cloud-generator.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: word-cloud-generator
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}