name: WCG worflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: wcg
  REGISTRY: ghcr.io
  OWNER: '${{ github.repository_owner }}'
  OWNER_LC: ''
  GITHUB_PAGES_URL: https://aleksandrhirs.github.io/devops-hometasks/

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Create and push tag
        uses: anothrNick/github-tag-action@1.64.0
        id: tag_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Test helm chart
        run: helm lint 12-helm/

      - name: Helm package
        run: helm package 12-helm/ --version ${{ steps.tag_version.outputs.new_tag }} --app-version ${{ steps.tag_version.outputs.new_tag }} -d charts

      - name: Update help index.yaml
        run: helm repo index . --url ${{ env.GITHUB_PAGES_URL }}

      - name: Commit helm package
        uses: stefanzweifel/git-auto-commit-action@v4

      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./07-docker
          file: ./07-docker/Dockerfile.multi
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:${{ steps.tag_version.outputs.new_tag }}