name: WCG worflow
on:
  workflow_dispatch:

env:
  IMAGE_NAME: wcg
  REGISTRY: ghcr.io
  OWNER: '${{ github.repository_owner }}'
  OWNER_LC: ''

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./07-docker
          file: ./07-docker/Dockerfile.multi
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:latest

#      - name: Create tag for new version
#        run: |
#          git config user.name "${{ github.actor }}"
#          git config user.email "${{ github.actor }}@users.noreply.github.com"
#          git tag -a v1.0.0 -m "Version 1.0.0"
#          git push origin v1.0.0
#
#      - name: Helm lint
#        run: helm lint ./12-helm
#
#      - name: Package Helm Chart
#        run: helm package ./12-helm
#
#      - name: Update repository index
#        run: helm repo index ./12-helm --url https://example.com/charts